all:
	mkdocs build
	mkdir -p ~/workspace/personal_website/tristartom.github.io/glsd2018
	cp -r *  ~/workspace/personal_website/tristartom.github.io/glsd2018/
	cd ~/workspace/personal_website/; ./tt_sh/commit.sh
