all:
	mkdocs build
	mkdir -p ~/workspace/personal_website/tristartom.github.io/glsd18
	cp -r *  ~/workspace/personal_website/tristartom.github.io/glsd18/
	cd ~/workspace/personal_website/; ./tt_sh/commit.sh
